In [1]:
# Javascript helps to add action
# Mouse events happen without refreshing the page using Javascript
# Javascript adds interactivity to web browsers

In [2]:
# Variables

In [3]:
# 6 primitive data types in Javascript

# 1) Number (both integral and decimal) (64 bit)
# 2) String
# 3) boolean
# 4) null
# 5) undefined
# 6) symbol

# And there is 1 object

# Variables in javascript are loosely typed. i.e A single variable can be used to store different types.

In [4]:
# Adding semi-colon at end of line is optional in javascript. Optional in the sense that Javascript will add semi-colon at the
# end of the line if there is no semicolon.

In [5]:
# console.log(a) prints the value of a to the console.

In [6]:
# variable declaration - We are just declaring a variable and not assigning any value to it
# variable definition - We are both declaring a variable and assigning value to it

# The undefined values don't have any garbage values in them. They just show as undefined.

In [7]:
# In the above, we set the value of a as null

In [8]:
# Infinity is a type in javascript
# 1/0 = infinity
# Math.pow(10, 1000) = Infinity. Any number that can't be stored (beyond the limits) is given the value of inifinity.

In [9]:
# Number.MAX_VALUE; gives the maximum number that can be stored in a number data type

In [10]:
# NaN - Not a number
# Examples - sqrt(-2), parseInt("hello")

In [11]:
# typeof operator

In [12]:
# output of above - "number"

In [14]:
# output of above - "object"
# The above is a bug in javascript

In [15]:
# output of above - "number"

In [16]:
# output of above - "number"
# This is strange

In [18]:
# output of above

# 6
# 6
# 7

In [19]:
# Logical operators - &&, ||, !

In [20]:
# Short circuit evaluation

In [21]:
# Output of above

# false
# 100

# In the above case, the value of b has not been incremented because of short circuit evaluation.

In [22]:
# Bitwise operators - >>, <<, &, |, >>>

In [ ]:
# output of above

# "hello world"
# "hello2"
# "11"
# -1
# 5
# 0.5
# false

In [23]:
# type coercion

# When you add a string and number, concatenation happens
# When a subtract/multiply/compare a string and number, automatic type conversion (known as type coercion) happens (i.e string is converted to number) and 
# the result is a number

In [24]:
# Operator precedence is 'multiplication', 'division', 'addition' and then 'subtraction'

In [25]:
# output of above

# undefinedb

In [ ]:
# == vs ===
# != vs !==

In [ ]:
# output of above

# true
# false
# false
# true

In [26]:
# Conditionals

In [27]:
# output of above

# Positive

In [ ]:
# block comments - /*, */
# line comments - //

In [28]:
# output of above

# True

In [29]:
# output of above

# False

In [1]:
# In javascript all the values have associated boolean values.

# In the case of numbers, anything other than 0 is considered to be true.
# In the case of strings, an empty string is considered false and any other string is considered true.
# If the variable is undefined or null, it will be treated as false.

In [2]:
# nul == undefined returns the boolean value true

In [3]:
# Loops

In [4]:
# While loop

In [5]:
# for loop

In [6]:
# do while loop

In [7]:
# output of above - string

In [9]:
# output of above - string

In [10]:
# output of above - undefined

In [11]:
# output of above - string

In [13]:
# output of above

# false
# true

In [14]:
# condition ? expressionIfTrue : expressionIfFalse;

In [28]:
import numpy as np
def sigmoid(z):
    return 1 / (1+np.exp(-z))

In [23]:
a = sigmoid(np.array([1,1.3,0.8]))
a

array([2.36787944, 2.27253179, 2.44932896])

In [25]:
np.dot(a,np.array([[0.3],
                   [0.5],
                   [0.9]]))

array([4.0510258])

In [26]:
np.array([])

array([], dtype=float64)

In [31]:
i = np.array([[1],[1]])
w1 = np.array([[0.8,0.4,0.3],[0.2,0.9,0.5]])
a = sigmoid(np.dot(np.transpose(w1),i))
a

array([[0.73105858],
       [0.78583498],
       [0.68997448]])

In [33]:
np.dot(np.array([[0.3,0.5,0.9]]),a)

array([[1.2332121]])